# Generated by Django 5.2.4 on 2025-07-17 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admins',
            field=models.ManyToManyField(limit_choices_to={'role': 'admin'}, related_name='admin_courses', to='userprofile.userprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='holders',
            field=models.ManyToManyField(limit_choices_to={'role': 'holder'}, related_name='holder_courses', to='userprofile.userprofile'),
        ),
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(limit_choices_to={'role': 'participant'}, related_name='participant_courses', to='userprofile.userprofile'),
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.userprofile'),
        ),
        migrations.AddField(
            model_name='question',
            name='courses',
            field=models.ManyToManyField(related_name='questions', to='core.course'),
        ),
        migrations.AddField(
            model_name='submission',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.course'),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(limit_choices_to={'role': 'participant'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='userprofile.userprofile'),
        ),
        migrations.AddField(
            model_name='submission',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.question'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='core.question'),
        ),
    ]
