# Generated by Django 5.2.4 on 2025-07-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_question_description'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='admins',
        ),
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'participant'}, related_name='participant_courses', to='userprofile.userprofile'),
        ),
    ]
