# Generated by Django 5.2.4 on 2025-07-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_course_admins_alter_course_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
