# Generated by Django 5.2.4 on 2025-07-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='questions', to='core.question'),
        ),
    ]
