# Generated by Django 5.2.4 on 2025-07-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testcase_author_alter_course_holders_and_more'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='holders',
            field=models.ManyToManyField(limit_choices_to={'role': 'holder'}, related_name='holder_courses', to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='situation',
            field=models.CharField(choices=[('correct', 'correct'), ('wrong', 'wrong')], max_length=10, null=True),
        ),
    ]
