# Generated by Django 5.2.4 on 2025-07-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_course_holders_alter_submission_situation'),
        ('userprofile', '0002_remove_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='holders',
            field=models.ManyToManyField(related_name='holder_courses', to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participant_courses', to='userprofile.userprofile'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='userprofile.userprofile'),
        ),
    ]
