# Generated by Django 5.2.4 on 2025-07-17 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('junior', 'junior'), ('mid_level', 'mid_level'), ('senior', 'senior')], default='junior', max_length=20)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('holder', 'Holder'), ('admin', 'Admin')], default='participant', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=50)),
                ('known_languages', models.ManyToManyField(blank=True, to='userprofile.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
